# Generated by Django 5.0.1 on 2024-02-21 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('nickname', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['nickname'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('winner_team', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('drafter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fixtures', to='stats.person')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixtures', to='stats.season')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_played', models.PositiveSmallIntegerField(choices=[('', '-'), (1, 1), (2, 2)])),
                ('goals', models.PositiveSmallIntegerField(default=0)),
                ('mvp_votes', models.PositiveSmallIntegerField(default=0)),
                ('is_mvp', models.BooleanField()),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='stats.fixture')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='played', to='stats.person')),
            ],
        ),
    ]
