# Generated by Django 5.0.1 on 2024-01-18 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixture',
            name='winner_team',
        ),
        migrations.AlterField(
            model_name='fixture',
            name='number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
