# Generated by Django 5.0.1 on 2024-01-18 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_remove_fixture_winner_team_alter_fixture_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='winner_team',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
