# Generated by Django 5.0.1 on 2024-01-18 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_fixture_winner_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='points_earned',
        ),
        migrations.AlterField(
            model_name='player',
            name='goals',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='mvp_votes',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
