# Generated by Django 5.0.1 on 2024-02-15 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_alter_person_options_remove_fixture_winner_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='winner_team',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
