# Generated by Django 5.0.1 on 2024-02-16 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0006_fixture_winner_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='diff',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixture',
            name='team_1_goals',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixture',
            name='team_2_goals',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='team_played',
            field=models.PositiveSmallIntegerField(choices=[('', '-'), (1, 1), (2, 2)]),
        ),
    ]
