# Generated by Django 5.0.1 on 2024-02-20 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0007_fixture_diff_fixture_team_1_goals_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixture',
            name='diff',
        ),
        migrations.RemoveField(
            model_name='fixture',
            name='team_1_goals',
        ),
        migrations.RemoveField(
            model_name='fixture',
            name='team_2_goals',
        ),
        migrations.RemoveField(
            model_name='fixture',
            name='winner_team',
        ),
    ]
